### ISSUE TITLE
simPlusPlus simulation step callback

### ISSUE THREAD

**Issue by jeguzzi** [CoppeliaRobotics/include#3]
Dear All,

I wrote plugins using simPlusPlus where I emulate the firmware of different robots. Typically I tick the robots' controller once per simulation step. Before version 4.6, I would use `void onModuleHandle(char *)`, which has since been removed. As `void onMsg(SSimMsg *)` is marked as `final`, I don't see a way to automatically receive notifications about simulation steps anymore. 

Am I missing something? Is there an alternative to `onModuleHandle`?

If not, is the designed way to go through a child scrip, ticking the controller explicitly, e.g., in `sysCall_actuation`?

**Comment by fferri** [comment]
You can override `void Plugin::onInstancePass(const InstancePassFlags &flags)`, monitoring simulation status (via `flags` or via the `onSimulationXXX` handlers.

**Comment by jeguzzi** [comment]
Thank you. My understanding is that `Plugin::onInstancePass` is tied to the main/renderer loop, therefore it is called several time per simulation step when running in real-time. Therefore, in order to run a callback only once per simulation step, I should read `simGetSimulationTime()` and check it against a state variable. This is surely possible but feels a bit cumbersome for such a common pattern.

May I suggest to either add handlers for all [non-deprecated] message ids in `Plugin::onMsg` or to remove the `final` from `Plugin::onMsg` so to let users overwrite it? In particular, handlers for `sim_message_eventcallback_simulationactuation` and `sim_message_eventcallback_simulationsensing` would be very useful.
