### ISSUE TITLE
Different constants with the same value

### ISSUE THREAD

**Issue by mfrigerio17** [CoppeliaRobotics/include#4]
Hi, I think there is a mistake at [this line](https://github.com/CoppeliaRobotics/include/blob/68873303cf65bc32845afe1b52c9db1376bbf2a0/simLib/simConst.h#L1327)

The constants `sim_visionintparam_rgbignored` _and_ `sim_visionintparam_depthignored` have the same value...

Indeed, setting one or the other within the Lua sandbox, for a vision sensor, results in both the checkboxes of the "scene object properties" tab to change.

**Comment by Coppelia** [comment]
Good catch, thanks! 
In next release sim_visionintparam_depthignored will be at 1021, breaking compatibility.
Cheers
